# Codecov Configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: '70...100'

  status:
    project:
      default:
        target: 80%
        threshold: 1%
        base: auto
        if_ci_failed: error

    patch:
      default:
        target: 80%
        threshold: 5%
        base: auto
        if_ci_failed: error

comment:
  layout: 'header, diff, flags, components, footer'
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

flags:
  backend:
    paths:
      - web/backend/src/
    carryforward: false

ignore:
  - '**/*.test.ts'
  - '**/*.spec.ts'
  - '**/*.d.ts'
  - '**/*.interface.ts'
  - '**/node_modules/'
  - '**/dist/'
  - '**/coverage/'
  - '**/__tests__/'
  - 'docs/'
  - 'scripts/'
  - 'infrastructure/'
